### PR TITLE
Denmpc ardrone gazebo

### PR DESCRIPTION
**Pull request by benjaminabruzzo**
I added a branch where I am trying to test out my configurations using gazebo.  

Right now I am getting a NaN error when I start the denmpc node in State[8].  I also added a readme for getting started in the gazebo branch.

process[scenario_scenario_node-1]: started with pid [25095]
Agent::Agent(id)
[ INFO] [1539629920.081544926]: ardrone_pose_topic: /vrpn_client_node/Ardrone/pose
[ INFO] [1539629920.081614262]: ardrone_desiredpose_topic: /usma_ardrone/mpc/desiredpose
[ INFO] [1539629920.081640041]: ardrone_ctrl_ch_topic: /usma_ardrone/uav/cmd_vel
Controller 0 CMSCGMRES Controller Constructor called
//*********************************************
// Starting Fast Cooperative Control Framework 
//*********************************************
// Initialization 
//---------------------------------------------
//---------------------------------------------
// Start VREP Control Loop 
!!! In : State[8] ERROR NAN DETECTED!

### CODE REVIEW

**Comment by DentOpt** [comment]
Hi,
state[8] is the yaw velocity. Accordingly, I suspect that maybe the pose topic is not initialised properly.
The quaternions used in PoseStamped always have to fulfil ||q||=1.
Accordingly, a quaternion q=[0,0,0,0] is not defined and will lead to nan.

In this context, I recommend you to check out "Ardrone_20170227.h".
There you can find how the PoseStamped messages are 
translated to the state-space model in the functions subStateCallback (regarding current state) and subDesiredStateCallback (regarding desired state).

I can recommend the eclipse/ros setup for debugging:
[wiki](http://wiki.ros.org/IDEs )

Let me know, if you have any further questions

**Comment by benjaminabruzzo** [comment]
Ah, I see. There is a dt computation in the desired state callback.  What rate/frequency do you use for updating the desired state?  I was only publishing it once, assuming the UAV would just keep trying to go there.

**Comment by DentOpt** [comment]
In this case, the velocities are derived by a simple finite difference quotient.
For the desired state xdes, the velocities v are based on:
```
v=(xdes-x)/dt
dt=(txdes - tx)
xdes: desired_position
x: current_system_position
txdes: des timestamp_when_xdes_was_published
tx: time_of_last_position_measurment
```
Accordingly, I recommend using rqt to send the desired pose in order to avoid crazy timestamps.
If you prefer to set the desired velocities to zero, you can also get rid of the finite difference in 
subDesiredStateCallback and the if dt>0 condition (Be careful to keep it in subStateCallback. There it is mandatory !!!).

However, I do not think this is the problem! Are you sure you don't send:

`rostopic pub /usma_ardrone/mpc/desiredpose geometry_msgs/PoseStamped '{header: {stamp: now, frame_id: "map"}, pose: {position: {x: 0.0, y: 0.0, z: 0.0}, orientation: {x: 0.0, y: 0.0, z: 0.0, w: 0.0}}}'`

instead of the normalized quaternion (with |orientation|=1 )

`rostopic pub /usma_ardrone/mpc/desiredpose geometry_msgs/PoseStamped '{header: {stamp: now, frame_id: "map"}, pose: {position: {x: 0.0, y: 0.0, z: 0.0}, orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}}}'`

Best regards,
Jan

**Comment by benjaminabruzzo** [comment]
There are two issues:
1) I was copying and pasting the line from the readme file where the pose is : pose: {position: {x: 1.0, y: 0.0, z: 1.0}, orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}}}.  I quickly made a node that just keeps publishing a pose to account for timing issues.  I recently pushed that up into my branch.

2) Neither of these addresses the State[8] NaN error, however it did create additional NaNs in the desired pose: 
!!! In : State[8] ERROR NAN DETECTED!
!!! In : Desired State[3] ERROR NAN DETECTED!
!!! In : Desired State[4] ERROR NAN DETECTED!
!!! In : Desired State[5] ERROR NAN DETECTED!
!!! In : Desired State[6] ERROR NAN DETECTED!
!!! In : Desired State[8] ERROR NAN DETECTED!

Thanks for being so responsive!

**Comment by DentOpt** [comment]
I am not sure what 1. and 2. is referring to.

If 1. is referring to use the normalized quaternion as you indicate, this should work.
Currently you are initializing the drone in DENMPC at position (0,0,2) oriented like the global coordinate frame (check "scenario.cpp"). 
```
double ardrone0_init_x[]=   {0,0,2, 1,0, 0.0,0.0,0.0,0.0};
double ardrone0_init_xdes[]={0,0,2, 1,0, 0.0,0.0,0.0,0.0};
```
Did you make sure that this is the position and **orientation** (as you have the error in the angular velocity) of the Ardrone in your simulation?
If you initialize the MPC solver to far of the actual position, it might have issues to converge at the beginning.

**Comment by benjaminabruzzo** [comment]
I think the State[8] error originates in the initialization of subscriber0_old_msg_ in the Ardrone_20170227.h file.

After adding a few ROS_INFO(); lines for debugging, the first time subStateCallback is called I get the following messages:

// Start VREP Control Loop 
[ INFO] [1539704783.170526957, 12.610000000]: dt: 0.6070
[ INFO] [1539704783.170549151, 12.610000000]: new  [x y z]: [1.1167 -0.1027 0.9792]
[ INFO] [1539704783.170559679, 12.610000000]: last [x y z]: [0.0000 0.0000 0.0000]
[ INFO] [1539704783.170570666, 12.610000000]: [newYaw lastYaw]: [-0.1425   -nan]
!!! In : State[8] ERROR NAN DETECTED!

However, after that the callback continues to function.  Is there a start message or a trigger that I need to call to start generating command messages to the ARDrone?

**Comment by DentOpt** [comment]
Ah, ok. I will try to change the initialisation to get rid of this error.
In "scenario.cpp" you should use 
`scheduler.run_control(0.01);`
instead of 
`scheduler.run_vrep(0.01);`
as otherwise the controller is trying to synchronize with the vrep simulator.

**Comment by benjaminabruzzo** [comment]
In Agent.h, lines 257-259, what do the following functions meaningfully accomplish:
`virtual void start(){printf("!!! Agent%i start: not defined \n",this->id_);};`
`virtual void pause(){printf("!!! Agent%i pause: not defined \n",this->id_);};`
`virtual void stop() {printf("!!! Agent%i stop:  not defined \n",this->id_);};`

When I start in "scheduler.run_control(0.01);" the "Agent%i start: not defined" message is thrown.

Also, followed by that error, another error is thrown: "*** stack smashing detected ***" after
`ptr_controller->computeAction(time_framework_);` 
is called in the control loop.  I've tracked it down to the constraints loop in Controller.cpp (void Controller::dldx(...)), but I'm not certain what is actually causing it.  My intuition is that there is a mismatch between 'ardrone0_init_p' and the constraint parameters.

**Comment by DentOpt** [comment]
Hi, these just templates.
These are virtual placeholders in case you want to implement routines for starting your robot.
E.g. you initialize your drone and at one point you press a start button which then executes this functions.
For your implementation, you can get rid of it or just ignore the error message.

Regarding the error msg:
Do you get the same error when you run the controller without the constraint in "scenario.cpp"?
e.g. (just with your rostopics):
```
#include "Scheduler.h"
#include "Agent.h"
#include "Constraint.h"
#include "Coupling.h"
#include "Ardrone_20170227.h"
#include "Cmscgmres.h"
#include "Event.h"
#include "std_msgs/Bool.h"

int main(int argc, char **argv){

//Initialize ros node
ros::init(argc, argv, "controller");

/****** Initialize Agent Instances ******/
	std::vector<Agent*> agentlist;

	//Initialize: Ardrone instance: ardrone1
	Ardrone_20170227* ardrone0=new Ardrone_20170227(agentlist.size());

	double ardrone0_init_p[]={ //without tracking position
			-0.5092,1.458,-1,1,-5,1.3,
			1.0,1.0,1.0, 1.0,1.0, 0.0,0.0,0.0,0.0,
			1.0,1.0,0.3,1.0
	};
	double ardrone0_init_x[]=   {0,0,2, 1,0, 0.0,0.0,0.0,0.0};
	double ardrone0_init_xdes[]={0,0,2, 1,0, 0.0,0.0,0.0,0.0};
	ardrone0->setInitialState(ardrone0_init_x);
	ardrone0->setInitialDesiredState(ardrone0_init_xdes);
	ardrone0->setInitialParameter(ardrone0_init_p);
	ardrone0->setStateSubscriberRosTopicName       ("/Ardrone2SimpleLinModel_HASHMARK_0/pose");
	ardrone0->setDesiredStateSubscriberRosTopicName("/Ardrone2SimpleLinModel_HASHMARK_0/desiredpose");
	ardrone0->setPublisherRosTopicName             ("/Ardrone2SimpleLinModel_HASHMARK_0/ext_ctrl_ch");
	agentlist.push_back(ardrone0); /*add to agentlist*/

/****** Initialize Coupling Instances ******/
	std::vector<Controller*> controllerlist;

	//Initialize: Controller
	Cmscgmres* controller1=new Cmscgmres(agentlist,controllerlist.size());
	controller1->setHorizonDiskretization(10);
	controller1->setHorizonLength(1);
	controller1->setTolerance(1e-8);
	controller1->setUpdateIntervall(0.01);
	controller1->setMaximumNumberofIterations(10);
	controller1->activateInfo_ControllerStates();
	controllerlist.push_back(controller1);


/****** Initialize Events ******/
	std::vector<Event*> eventlist;

/****** Initialize Scheduler ******/
	Scheduler scheduler(argc,argv,controllerlist, eventlist);
	scheduler.run_control(0.01);
};
```
Best regards,
Jan

**Comment by benjaminabruzzo** [comment]
No, I do not get the same error after commenting out the constraint lines in scenario.cpp.

It does not seem like the controller is generating cmd messages to the ar.drone, is there a place where I need to switch on the controller?

**Pull request closed without merging**
